name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: npm ci
        run: npm ci --prefix app
      - name: Build
        env:
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_GOOGLE_CALENDER_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CALENDER_CLIENT_ID }}
          VITE_GOOGLE_CALENDER_CLIENT_SECRET: ${{ secrets.VITE_GOOGLE_CALENDER_CLIENT_SECRET }}
          VITE_GOOGLE_CALENDER_REDIRECT_URI: ${{ secrets.VITE_GOOGLE_CALENDER_REDIRECT_URI }}
          VITE_GOOGLE_CALENDER_apiKey: ${{ secrets.VITE_GOOGLE_CALENDER_apiKey }}
          VITE_GOOGLE_CALENDER_scope: ${{ secrets.VITE_GOOGLE_CALENDER_scope }}
          VITE_GOOGLE_CALENDER_discoveryDocs: ${{ secrets.VITE_GOOGLE_CALENDER_discoveryDocs }}
        run: npm run build --prefix app
      - name: ci function
        run: npm --prefix functions ci
      - name: build functions
        run: npm --prefix functions run build
      - name: Run tests
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: npm --prefix functions test
      - name: Deploy Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --force
        env:
          PROJECT_ID: cyclictodo
          GCP_SA_KEY: ${{ secrets.GCP_SA }}
          PROJECT_PATH: ./functions

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CYCLICTODO }}"
          channelId: live
          projectId: cyclictodo
