name: マスターへのマージ時にFirebase Hostingへデプロイ

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      # アプリケーションの依存関係をインストール
      - name: アプリケーションの依存関係をインストール
        run: npm ci --prefix app

      # アプリケーションのビルド
      - name: アプリケーションのビルド
        env:
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_GOOGLE_CALENDAR_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CALENDAR_CLIENT_ID }}
          VITE_GOOGLE_CALENDAR_CLIENT_SECRET: ${{ secrets.VITE_GOOGLE_CALENDAR_CLIENT_SECRET }}
          VITE_GOOGLE_CALENDAR_REDIRECT_URI: ${{ secrets.VITE_GOOGLE_CALENDAR_REDIRECT_URI }}
          VITE_GOOGLE_CALENDAR_API_KEY: ${{ secrets.VITE_GOOGLE_CALENDAR_API_KEY }}
          VITE_GOOGLE_CALENDAR_SCOPE: ${{ secrets.VITE_GOOGLE_CALENDAR_SCOPE }}
          VITE_GOOGLE_CALENDAR_DISCOVERY_DOCS: ${{ secrets.VITE_GOOGLE_CALENDAR_DISCOVERY_DOCS }}
        run: npm run build --prefix app

      # エンティティの依存関係をインストール
      - name: エンティティの依存関係をインストール
        run: npm ci --prefix entity

      # 関数の依存関係をインストール
      - name: 関数の依存関係をインストール
        run: npm ci --prefix functions

      # 関数のテストを実行
      - name: 関数のテストを実行
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: npm test --prefix functions

      # 関数のビルド
      - name: 関数のビルド
        run: npm run build --prefix functions

      # Firebase CLIのインストール
      - name: Firebase CLIのインストール
        run: npm install -g firebase-tools

      # Firebase Functionsのデプロイ
      - name: Firebase Functionsのデプロイ
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --force
        env:
          PROJECT_ID: cyclictodo
          GCP_SA_KEY: ${{ secrets.GCP_SA }}
          PROJECT_PATH: ./functions

      # Firebase Hostingへのデプロイ
      - name: Firebase Hostingへのデプロイ
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CYCLICTODO }}"
          channelId: live
          projectId: cyclictodo
