name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make the script executable
        run: chmod +x scripts/export-import-indexes.sh
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Write Firebase Service Account Key
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CYCLICTODO }}" > /tmp/service-account.json
      - name: Export and Import Firestore Indexes
        run: ./scripts/export-import-indexes.sh
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA }}
      - run: npm ci
      - name: Build
        env:
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}
          REACT_APP_GOOGLE_CALENDER_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CALENDER_CLIENT_ID }}
          REACT_APP_GOOGLE_CALENDER_CLIENT_SECRET: ${{ secrets.REACT_APP_GOOGLE_CALENDER_CLIENT_SECRET }}
          REACT_APP_GOOGLE_CALENDER_REDIRECT_URI: ${{ secrets.REACT_APP_GOOGLE_CALENDER_REDIRECT_URI }}
          REACT_APP_GOOGLE_CALENDER_apiKey: ${{ secrets.REACT_APP_GOOGLE_CALENDER_apiKey }}
          REACT_APP_GOOGLE_CALENDER_scope: ${{ secrets.REACT_APP_GOOGLE_CALENDER_scope }}
          REACT_APP_GOOGLE_CALENDER_discoveryDocs: ${{ secrets.REACT_APP_GOOGLE_CALENDER_discoveryDocs }}
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CYCLICTODO }}"
          channelId: live
          projectId: cyclictodo
